FROM node:22-alpine

WORKDIR /app

# Копируем package.json корневого проекта
COPY package*.json ./

# Устанавливаем зависимости сервера
RUN npm install

# Копируем package.json клиента и устанавливаем зависимости
COPY client/package*.json ./client/
RUN npm run client:install

# Копируем остальные файлы проекта
COPY . .

EXPOSE 5000
EXPOSE 3000

# Команда для запуска
CMD ["sh", "-c", "npm run server & npm run client"]